os:
  - linux
language: rust
cache: cargo # cache cargo-audit once installed
before_script:
  - travis_wait 30 rustup override set nightly
  - travis_wait 30 rustup update
  - travis_wait 30 cargo update
  - travis_wait 30 cargo install --force cargo-audit
  - travis_wait 30 cargo generate-lockfile
script:
  #- cargo test
  - travis_wait 30 cargo build --features=fail-on-warnings --manifest-path ./racer/Cargo.toml
  - travis_wait 30 cargo build --features=fail-on-warnings --manifest-path ./server/Cargo.toml
  - travis_wait 30 cargo build
  - cargo audit
