[development]
address = "localhost"
port = 42069
keep_alive = 5
log = "normal"
limits = { forms = 32768 }

[staging]
address = "0.0.0.0"
port = 42069
keep_alive = 5
log = "normal"
limits = { forms = 32768 }

[production]
address = "0.0.0.0"
port = 42069
keep_alive = 5
log = "normal"
limits = { forms = 32768 }
