[global]
host = "http://podracer.zachn.me"
template_dir = "templates/"

[development]
address = "localhost"
port = 42069
keep_alive = 5
log = "normal"
limits = { forms = 32768 }
update_factor = 1

[staging]
address = "0.0.0.0"
port = 42069
keep_alive = 5
log = "normal"
limits = { forms = 32768 }
update_factor = 45

[production]
address = "0.0.0.0"
port = 42069
keep_alive = 5
log = "normal"
limits = { forms = 32768 }
update_factor = 45
