[global]
workers=8
port = 41968
keep_alive = 5
limits = { forms = 32768 }

[debug]
update_factor = 1
host = "http://localhost:41968"
static_file_dir = "/Users/z/code/PodRacer/server/web/static"
podracer_dir = "/Users/z/.config/podcasts.dev"
template_dir = "server/web/templates"

[staging]
address = "0.0.0.0"
update_factor = 45
host = "http://podracer.zachn.me"
static_file_dir = "/etc/podracer/config/server/web/static"
podracer_dir = "/etc/podracer/podcasts.staging"
template_dir = "server/web/templates"

[release]
address = "0.0.0.0"
update_factor = 45
host = "http://podracer.zachn.me"
static_file_dir = "/etc/podracer/config/server/web/static"
podracer_dir = "/etc/podracer/podcasts"
template_dir = "server/web/templates"

[docker]
address = "0.0.0.0"
update_factor = 45
host = "http://localhost:42609"
static_file_dir = "server/static"
podracer_dir = "podcasts"
template_dir = "server/templates"
