[global]
workers=32
template_dir = "server/web/templates/"
#template_dir = "server/templates/"

[development]
address = "localhost"
port = 42069
keep_alive = 5
log = "normal"
limits = { forms = 32768 }
update_factor = 1
host = "http://localhost:42069"
static_file_dir = "/Users/znielsen/code/PodRacer/server/web/static"
podracer_dir = "/Users/znielsen/.config/pod_racer"

[staging]
address = "0.0.0.0"
port = 42069
keep_alive = 5
log = "normal"
limits = { forms = 32768 }
update_factor = 45
host = "http://podracer.zachn.me"
static_file_dir = "/etc/podracer/config/server/web/static"
podracer_dir = "/etc/podracer/podcasts"

[production]
address = "0.0.0.0"
port = 42069
keep_alive = 5
log = "normal"
limits = { forms = 32768 }
update_factor = 45
host = "http://podracer.zachn.me"
static_file_dir = "/etc/podracer/config/server/web/static"
podracer_dir = "/etc/podracer/podcasts"

