[global]
template_dir = "server/web/templates/"
tls.certs = "/etc/letsencrypt/live/podracer.zachn.me/fullchain.pem"
tls.key = "/etc/letsencrypt/live/podracer.zachn.me/privkey.pem"

[development]
address = "localhost"
port = 42069
keep_alive = 5
log = "normal"
limits = { forms = 32768 }
update_factor = 1
host = "http://localhost:42069"

[staging]
address = "0.0.0.0"
port = 80
keep_alive = 5
log = "normal"
limits = { forms = 32768 }
update_factor = 45
host = "http://podracer.zachn.me"

[production]
address = "0.0.0.0"
port = 80
keep_alive = 5
log = "normal"
limits = { forms = 32768 }
update_factor = 45
host = "http://podracer.zachn.me"
