name: Docker-Publish

on:
  workflow_dispatch:
#  push:
#    branches:
#      - 'main'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      # Credit to the workaround: https://github.com/rust-lang/cargo/issues/8719#issuecomment-977690631
      - name: Set Swap Space
        uses: pierotofy/set-swap-space@v1.0
        with:
          swap-size-gb: 10
      - run: |
          # Workaround for https://github.com/rust-lang/cargo/issues/8719
          sudo mkdir -p /var/lib/docker
          sudo mount -t tmpfs -o size=10G none /var/lib/docker
          sudo systemctl restart docker
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: |
            ghcr.io/${{ github.repository_owner }}/podracer:latest
          platforms: linux/amd64
          #platforms: linux/arm/v7,linux/amd64,linux/arm64 #linux/386
